- config/configure.py
- reload
`prometheus.yml` is created from a template by the `configure` script, so we need to run `configure` before reloading for changes to that config to take effect
> configure before a reload

- README.md
This one turned out to be no code at all. I have moved around the files on support - see the other https://github.com/vimc/montagu-machine/pull/8 in montagu-machine for more details
> i2497: Update instructions to use `sudo` only where needed

- config/prometheus/alert-rules.yml
This alert tells us nothing useful and pollutes the slack channel. Will be replaced longer term by https://vimc.myjetbrains.com/youtrack/issue/VIMC-2398
> remove shrunk backup alert

- README.md
- config/alertmanager.template.yml
- config/prometheus.template.yml
- config/prometheus/alert-rules.yml
- rewrite proxy instance labels to use human readable names: "UAT", "Science" etc
- make proxy down alerts fire more frequently than the others, we want to be alerted every 20mins if they remain down
> Improve proxy metric alerts

- config/prometheus/alert-rules.yml
This moves the message to the same format as other (THING on PLACE is PROBLEM)
but this is mostly so that the machine name does not get tangled up with
the markdown formatting when it comes through to slack
> VIMC-2887: Restructure log message

- .gitignore
- config/alertmanager.template.yml
- config/config.template.ini
- config/configure.py
- config/prom2teams/alarm-template.j2
- config/prometheus.template.yml
- config/prometheus/alert-rules.yml
- docker-compose.yml
This is a non Montagu app - longer term, do we want a separate monitor instance, or do we move this over to being a general RESIDE instance?
This PR also moves the notifications over from Slack to Teams. It was simple to get this set up but took me *forever* to customise the message to something reasonably nice looking in Teams! Predictably tragic emoji support :disappointed: 
I've set this up to go to a new channel `reside-monitor`. It's been running from my laptop so you can see the output in that channel. We shouldn't deploy this until HINT is deployed with a metrics endpoint, otherwise the `HintDown` alert will keep firing. HINT PR here: https://github.com/mrc-ide/hint/pull/368
> mrc-1845 add hint up rule

- README.md
- config/alertmanager.template.yml
- config/configure.py
- config/prometheus.template.yml
- config/prometheus/alert-rules.yml
- docker-compose.yml
This PR handles a few small things
* Move alerts back to slack from teams (I haven't removed all the teams config as I suppose we might want it later, but this will no longer post to teams after this change).
* Updates the slack integration to now use `postMessage` instead of the webhooks. Looks like webhooks are not only per channel, cannot define a webhook which can access multiple channels. So instead gone for the approach of using a bot oauth token to authenticate and then use `postMessage` API route
* Added a button into the post "Silence" which will open a link to view docs on how to silence an alert
* Reduced the frequency of OW on UAT alerts to every 24 hours
* Added separate alerting for hint. hint alerts will go to `hint-monitor` channel and all other alerts to `montagu-monitor` …
> vimc-7144: Move alerts back onto slack

- config/configure.py
- config/grafana/datasource.yml
- config/prometheus.template.yml
- config/prometheus/alert-rules.yml
- docker-compose.yml
- reload
This PR will
* Run up Grafana instance pointed to prometheus as data source
* Add alert when disk space is over 80%
* Add an alert when disk space will fill up in next 2 weeks (might be obsolete with the above alert)
I've also updated the knowledge base article on monitoring https://mrc-ide.myjetbrains.com/youtrack/articles/RESIDE-A-22/Monitoring
There are instructions there for how to view the system monitor, at the moment this is available for hint instances, buildkite agents, montagu prod and annex
Here is a screenshot where we can see the spike in usage from the other morning when people were using the app in Uganda
I will add a proxy around this as a next step. I think this will address ticket [mrc-3920](https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-3920) too
> reside-362: Add grafana to monitoring setup and alert on disk usage

- config/prometheus.template.yml
- reload
Naomi production was down for a couple of hours but we didn't get any alerts.. so something was up. Turns out prometheus has just not been communicating with alertmanager. Think this must have been since I did the last bit of work on this ~ 5 months ago :scream: 
Can confirm we are getting alerts after this https://resideglobal.slack.com/archives/C05HQMH482H/p1719482721208409
I also fixed up the reload script which had also rotted
> Fix issue with prometheus connecting to alertmanager

- config/prometheus.template.yml
Rather than hardcoding a list of targets to scrape, the configuration uses an HTTP-based service discovery. The packit.dide.ic.ac.uk machine is configured to expose a JSON document on port 9000. This will allow Prometheus to automatically discover new endpoints as we add new instances.
Currently, the services being exposed are one node_exporter for the whole machine, and one outpack_server for each instance hosted on the server. Packit does not yet have a metrics endpoint.
> Scrape packit.dide.ic.ac.uk 

- config/prometheus.template.yml
We've taken these deployments down, removing the alerts for them
> Remove naomi dev and staging from alert config

- config/prometheus.template.yml
Just like the existing packit server, this uses HTTP-based service discovery to determine the list of all services running on the host.
> Add scrape configurations for packit-private.

- config/prometheus.template.yml
The relabel rule was trying to rewrite the instance label, but was not working. It seems as though at the point where it runs there is no instance label yet. It only gets set later in the process to `__address__` if not set anywhere else.
Using `__address__` directly fixes that and makes the relabel rule work as intended.
> Fix the relabel config for Packit.

- reload
As part of vimc/montagu-monitor#40 I changed the nginx configuration such that it redirects to TLS for all hostnames, not just the `bots.dide.ic.ac.uk`. This was done to simplify the nginx configuration and not need any templating of the file based on the domain name.
It wouldn't have made any difference since the server is only ever accessed through that domain name, if not for the reload script, which uses `localhost` to access the server.
Because of this, the reload script now gets redirected to TLS and fails validation because the hostname in the certificate is not "localhost".
There's a bunch of ways this could be fixed, but the simplest is to just skip TLS validation in the reload script. This is a local communication anyway and we aren't sending any actual information in the …
> Skip TLS cert verification when reloading.

- .gitignore
- config/configure.py
- config/prometheus/prometheus.yml
- docker-compose.yml
- reload
- run
- stop
Using mako as a templating tool adds an extra layer of complexity that isn't necessary. The only two uses were to load a list of targets and to provide AWS credentials, both of which can be achieved through other means.
This also updates to docker compose v2 syntax.
> Simplify the prometheus template.

- config/prometheus/prometheus.yml
- docker-compose.yml
This will help keep an eye of the size and growth of the database, as well as queries latency. I was initially hoping to monitor error rates as well, but it seems our Redis instance is fairly old and doesn't expose these statistics.
This uses redis-exporter as a bridge between redis and prometheus. In theory a single instance of the exporter can be used to monitor any number of redis server's, although at the moment only the wpia-hn is configured. We may want to add hint and/or daedalus' servers in the future.
It seems redis has native support for prometheus in [its enterprise offering][redis-metrics], but not something we get to use.
[redis-metrics]: https://redis.io/docs/latest/integrate/prometheus-with-redis-enterprise/prometheus-metrics-definitions/
> Add scraping of wpia-hn's redis instance.

- config/grafana/datasource.yml
- config/prometheus/prometheus.yml
When using the `rate()` operator, one needs to provide a suitable interval. Grafana provides a `$__rate_interval` variable that can be used as the interval, however this variable only works correctly if Grafana knows about Prometheus' scrape interval.
Unfortunately, Prometheus' default scrape interval is one minute, whereas Grafana assumes it to be 15 seconds. This breaks the automatic rate interval when zooming in too much.
https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/
> Set the correct scrape interval in Grafana.

- config/grafana/datasource.yml
The file had been copied from the website and contained a lot of unnecessary entries. Some of it already matched the default values and some of it was entirely unused (eg. options that apply to non-prometheus data sources only).
I've cleaned it up to contain only the essential bits. I've also removed the `deleteDatasources` section: rather than deleting and creating new data sources, Grafana can update the existing one. The behaviour is roughly equivalent.
> Clean up the datasource.yml file.

- config/prometheus/alert-rules.yml
- config/prometheus/blackbox-probes.yaml
- config/prometheus/prometheus.yml
- docker-compose.yml
This adds an HTTPS probe for all the services we run. It can allow us to at a glance check the liveness of our services. It also reports certificate expiry time.
The list of services is the union from a list provided by Wes and a search for valid as of today certificates for 'dide.ic.ac.uk' subdomains on crt.sh.
```sh
curl -s 'https://crt.sh/json?dnsname=dide.ic.ac.uk&exclude=expired' | jq -r 'map(.common_name) | unique | .[]'
```
Some hostnames were excluded:
- `naomi-dev.dide` and `naomi-staging.dide` don't exist anymore won't be coming back.
- `hipercow.dide` does not exist yet
- `ebola2018.dide`, `mpox.dide` and `ncov.dide` are presumed to have been decomissioned.
- `orderly.dide`, `hiv-orderly.dide`, `malaria-orderly.dide` don't seem to exist, and are superseeded by Packit.
- …
> Add blackbox probes for most of our services.

- docker-compose.yml
Alertmanager stores its silences on disk at the `/alertmanager` path. Unless we mount a volume at that location, all silences are lost whenever the container is restarted, leading to lots of noise and redundant alerts.
Mounting a volume at that location fixes the issue.
> Add a volume for alertmanager's data.

- config/grafana/grafana.template.ini
We have a shared password (stored in Vault) that is used to restrict access to Grafana. Given that Prometheus, the underlying datasource, already allows unauthenticated access to the metrics, putting access restrictions on Grafana doesn't protect anything and makes sharing dashboards with other people tedious.
Modifying dashboards will still require logging in. A "Sign in" button is present in the top-right of the webpage.
https://grafana.com/docs/grafana/v11.4/setup-grafana/configure-security/configure-authentication/#anonymous-authentication
> Allow anonymous access to Grafana.

- config/alertmanager.template.yml
- config/prometheus/alert-rules.yml
- docker-compose.yml
These are not time sensitive or of a high severity. We only have those alerts to avoid forgetting to deploy. Once a week notice is enough (it already takes a week to fire the first time).
For this to work we need to increase alertmanager's data retention period, now at two weeks. The default value was 120h.
> Reduce the frequency of PackitConfigDrift alerts.

- config/prometheus/prometheus.yml
To avoid wasting GitHub rate limit credit, we were using a long scrape interval (10 minutes) on the GitHub exporter. Unfortunately, after 5 minutes Prometheus considers the samples to be stale, which could lead to some alerts and confusing graphs.
GitHub's rate limit for unauthenticated request is 60 per hour. Using 3 minutes as the scraping interval leads to 20 requests per minute, assuming we only need one request per scrape, which is currently the case.
If rate limit ever becomes a big concern, we can start using an access token which will raise the limit to 5000 requests per hour.
Alternatively, we can introduce caching inside the exporter and use conditional requests to the GitHub API. According to GitHub, if their API returns a 304 response the request is not counted towards our …
> Increase the scrape rate of the GitHub exporter.

- config/prometheus/alert-rules.yml
By default Certbot renews Let's Encrypt certificates 30 days before they are due to expire. We had an alert set to the same period, which would fire and notify us even though certbot was about to perform the renewal.
Using a shorter duration will avoid this issue. 21 days (or three weeks) seems like a reasonable value, giving us enough time to intervene manually if necessary.
We could make the rule conditional on the issuer, eg. use a shorter duration for automatically issued certificates and a longer one for manually issued ones, but that doesn't seem worth the extra complexity.
> Reduce the TLS expiry from 30 days to three weeks.

- config/prometheus/alert-rules.yml
This adds the missing `_bytes` suffix to the `node_filesystem_free` metric used by the alert. The name was changed way back in node_exporter 0.16.0, released in 2018. I suspect this alert has never actually worked.
I've also changed the range used to calculate the linear interpolation from 1 hour to 1 day. It is reasonably easy for a sudden download to trigger the alert when extrapolating one hour to two weeks: a 3GB increase over an hour is roughly 1TB over two weeks. Using a whole day should help avoid false positives.
> Fix and improve DiskWillFillIn2Weeks metric.

- config/prometheus/prometheus.yml
This will let us monitor occupancy and disk usage.
I installed the node_exporter by simply using `apt install prometheus-node-exporter` instead of the ["machine-metrics"][machine-metrics] scripts we have used in the past.
NVidia also offers [an exporter to gather GPU-specific metrics][dcgm-exporter]. For now this is only running on gpu-01, as the package I installed isn't available on the old Ubuntu distribution that is running on gpu-02.
```
sudo apt install datacenter-gpu-manager-4-cuda12 datacenter-gpu-manager-exporter
sudo systemctl enable --now nvidia-dcgm-exporter.service
```
[machine-metrics]: https://github.com/vimc/machine-metrics
[dcgm-exporter]: https://docs.nvidia.com/datacenter/dcgm/latest/gpu-telemetry/dcgm-exporter.html
> Add exporters for wpia-gpu-01 and wpia-gpu-02.

- config/prometheus/alert-rules.yml
It has been more noise than signal. We have the 80% alert instead which should be enough.
> Remove DiskWillFillIn2Weeks alert.

- config/prometheus/alert-rules.yml
CIFS mounts represent network drives. These are managed externally and do not represent the health of the individual machines.
While it might be useful to have an eye on these drives, if we do it we should do it in a consistent way, not just on the drives that we happen to have mounted.
For reference the Climate drive (mounted on GPU-02) is currently at 83% occupation, and the Q drive (mounted on GPU-01) is just under 80%.
> Exclude cifs mountpoints from the disk space alerts.

- config/prometheus/prometheus.yml
We managed to run out of disk space on that VM without any warning. Running node_exporter and monitoring it gives us our usual 80% disk usage alerts.
> Scrape node_exporter from bots.

- config/alertmanager/templates/slack-alert-text.tmpl
The alert template was using minus signs in its directives to suppress superfluous whitespaces. This had the unintended consequence of putting all the bullets on the same line in cases where alerts have been grouped together.
See the [text/template][godocs] documentation for reference about the template syntax.
[godocs]: https://pkg.go.dev/text/template#hdr-Text_and_spaces
The Slack API that alertmanager uses to post Slack messages doesn't actually support formatted bullet points, but separate lines with leading asterisks is good enough.
> Add missing newline between alert bullet points.

- playbooks/DiskNearlyFull.md
We now mount the large data disk onto /home directly. No need to ask users to move anything anymore.
> Update DiskNearlyFull playbook.

- config/prometheus/alert-rules.yml
The alert makes sure that every certificate obtained by acme-buddy has been loaded by the relevant http server.
We used to join on the instance/domain label, however a recent change to the configuration of the blackbox exporter means that the instance of `probe_ssl_last_chain_info` is now a full URL rather than just a domain name.
We could try to extract the domain name out of the URL to keep matching on it, but to be honest I don't believe that join criteria adds that much value. If the certificate had been loaded for a different domain name the blackbox exporter would fail TLS verification and the `probe_ssl_last_chain_info` metric would never show up. Removing that criteria is simpler.
> Relax the AcmeBuddyCertificateNotLoaded alert.

- config/prometheus/linux-nodes.yaml
The VMs running on hn2 use the hpc.dide.ic.ac.uk. The hpc portion of that was missing.
> Fix hostname of HPC VMs.
